# These are supported funding model platforms

github: [yllada]
# patreon: # Replace with your Patreon username
# open_collective: # Replace with your Open Collective username
# ko_fi: # Replace with your Ko-fi username
# tidelift: npm/package-name
# community_bridge: # Replace with project name
# liberapay: # Replace with your Liberapay username
# issuehunt: # Replace with your IssueHunt username
# lfx_crowdfunding: # Replace with project name
# polar: # Replace with your Polar username
custom: # ['https://www.buymeacoffee.com/yourname']
